grpc:
  server:
    port: 19999
server:
  port: 20003
spring:
  application:
    name: huang-provider-20003
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.194.152:8848
        enabled: true
