grpc:
  client:
    #服务名称
    huang-provider-20003:
      negotiation-type: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
server:
  port: 20004
spring:
  application:
    name: huang-consumer-20004
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.194.152:8848
        enabled: true
